-- Code generated by protoc-gen-workato. DO NOT EDIT.

local M = {}

function M.get_workato_bucket(method, path)
  if method == "DELETE" then
    if path:match('^/v1/tasks/.+$') then
      return "api.tasks.v1.TasksService"
    end

    return "other"
  end
  if method == "GET" then
    if path:match('^/v1/tasks/.+$') then
      return "api.tasks.v1.TasksService"
    end

    return "other"
  end
  if method == "POST" then
    if path == "/api.tasks.v1.TasksService/CreateTask" then
      return "/api.tasks.v1.TasksService/CreateTask"
    end
    if path == "/v1/tasks" then
      return "/api.tasks.v1.TasksService/CreateTask"
    end
    if path == "/api.tasks.v1.TasksService/GetTask" then
      return "api.tasks.v1.TasksService"
    end
    if path == "/api.tasks.v1.TasksService/UpdateTask" then
      return "api.tasks.v1.TasksService"
    end
    if path == "/api.tasks.v1.TasksService/DeleteTask" then
      return "api.tasks.v1.TasksService"
    end
    if path == "/api.tasks.v1.TasksService/AddComment" then
      return "custom_bucket:TaskComments"
    end
    if path == "/api.tasks.v1.TasksService/UpdateComment" then
      return "custom_bucket:TaskComments"
    end
    if path:match('^/v1/tasks/.+/comment$') then
      return "custom_bucket:TaskComments"
    end

    return "other"
  end
  if method == "PUT" then
    if path:match('^/v1/tasks/.+$') then
      return "api.tasks.v1.TasksService"
    end
    if path:match('^/v1/tasks/.+/comment/.+$') then
      return "custom_bucket:TaskComments"
    end

    return "other"
  end

  return "other"
end

return M
