// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: fixtures/tasks.proto

package tasks

import (
	_ "github.com/SafetyCulture/protoc-gen-workato/s12/protobuf/workato"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/visibility"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTasksRequest_Status int32

const (
	ListTasksRequest_UNKNOWN  ListTasksRequest_Status = 0
	ListTasksRequest_ACTIVE   ListTasksRequest_Status = 1
	ListTasksRequest_ARCHIVED ListTasksRequest_Status = 2
)

// Enum value maps for ListTasksRequest_Status.
var (
	ListTasksRequest_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "ARCHIVED",
	}
	ListTasksRequest_Status_value = map[string]int32{
		"UNKNOWN":  0,
		"ACTIVE":   1,
		"ARCHIVED": 2,
	}
)

func (x ListTasksRequest_Status) Enum() *ListTasksRequest_Status {
	p := new(ListTasksRequest_Status)
	*p = x
	return p
}

func (x ListTasksRequest_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListTasksRequest_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_fixtures_tasks_proto_enumTypes[0].Descriptor()
}

func (ListTasksRequest_Status) Type() protoreflect.EnumType {
	return &file_fixtures_tasks_proto_enumTypes[0]
}

func (x ListTasksRequest_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListTasksRequest_Status.Descriptor instead.
func (ListTasksRequest_Status) EnumDescriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{1, 0}
}

type TriggerTaskRequest_TriggerEvent int32

const (
	// Unspecified Event
	TriggerTaskRequest_TRIGGER_EVENT_UNSPECIFIED TriggerTaskRequest_TriggerEvent = 0
	// Task 'Started'
	TriggerTaskRequest_TRIGGER_EVENT_TASK_CREATED TriggerTaskRequest_TriggerEvent = 1
	// Task Updated
	TriggerTaskRequest_TRIGGER_EVENT_TASK_UPDATED TriggerTaskRequest_TriggerEvent = 2
	// Task Closed
	TriggerTaskRequest_TRIGGER_EVENT_TASK_CLOSED TriggerTaskRequest_TriggerEvent = 3
	// Task Deleted
	TriggerTaskRequest_TRIGGER_EVENT_TASK_DELETED TriggerTaskRequest_TriggerEvent = 4
)

// Enum value maps for TriggerTaskRequest_TriggerEvent.
var (
	TriggerTaskRequest_TriggerEvent_name = map[int32]string{
		0: "TRIGGER_EVENT_UNSPECIFIED",
		1: "TRIGGER_EVENT_TASK_CREATED",
		2: "TRIGGER_EVENT_TASK_UPDATED",
		3: "TRIGGER_EVENT_TASK_CLOSED",
		4: "TRIGGER_EVENT_TASK_DELETED",
	}
	TriggerTaskRequest_TriggerEvent_value = map[string]int32{
		"TRIGGER_EVENT_UNSPECIFIED":  0,
		"TRIGGER_EVENT_TASK_CREATED": 1,
		"TRIGGER_EVENT_TASK_UPDATED": 2,
		"TRIGGER_EVENT_TASK_CLOSED":  3,
		"TRIGGER_EVENT_TASK_DELETED": 4,
	}
)

func (x TriggerTaskRequest_TriggerEvent) Enum() *TriggerTaskRequest_TriggerEvent {
	p := new(TriggerTaskRequest_TriggerEvent)
	*p = x
	return p
}

func (x TriggerTaskRequest_TriggerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerTaskRequest_TriggerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_fixtures_tasks_proto_enumTypes[1].Descriptor()
}

func (TriggerTaskRequest_TriggerEvent) Type() protoreflect.EnumType {
	return &file_fixtures_tasks_proto_enumTypes[1]
}

func (x TriggerTaskRequest_TriggerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerTaskRequest_TriggerEvent.Descriptor instead.
func (TriggerTaskRequest_TriggerEvent) EnumDescriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{16, 0}
}

type GenerateReportRequest_ReportFormatWrapper_ReportFormat int32

const (
	GenerateReportRequest_ReportFormatWrapper_UNKNOWN GenerateReportRequest_ReportFormatWrapper_ReportFormat = 0
	// CSV Format
	GenerateReportRequest_ReportFormatWrapper_CSV GenerateReportRequest_ReportFormatWrapper_ReportFormat = 1
	// TSV Format
	GenerateReportRequest_ReportFormatWrapper_TSV GenerateReportRequest_ReportFormatWrapper_ReportFormat = 2
	// Hidden format
	GenerateReportRequest_ReportFormatWrapper_HIDDEN GenerateReportRequest_ReportFormatWrapper_ReportFormat = 3
)

// Enum value maps for GenerateReportRequest_ReportFormatWrapper_ReportFormat.
var (
	GenerateReportRequest_ReportFormatWrapper_ReportFormat_name = map[int32]string{
		0: "UNKNOWN",
		1: "CSV",
		2: "TSV",
		3: "HIDDEN",
	}
	GenerateReportRequest_ReportFormatWrapper_ReportFormat_value = map[string]int32{
		"UNKNOWN": 0,
		"CSV":     1,
		"TSV":     2,
		"HIDDEN":  3,
	}
)

func (x GenerateReportRequest_ReportFormatWrapper_ReportFormat) Enum() *GenerateReportRequest_ReportFormatWrapper_ReportFormat {
	p := new(GenerateReportRequest_ReportFormatWrapper_ReportFormat)
	*p = x
	return p
}

func (x GenerateReportRequest_ReportFormatWrapper_ReportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateReportRequest_ReportFormatWrapper_ReportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_fixtures_tasks_proto_enumTypes[2].Descriptor()
}

func (GenerateReportRequest_ReportFormatWrapper_ReportFormat) Type() protoreflect.EnumType {
	return &file_fixtures_tasks_proto_enumTypes[2]
}

func (x GenerateReportRequest_ReportFormatWrapper_ReportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateReportRequest_ReportFormatWrapper_ReportFormat.Descriptor instead.
func (GenerateReportRequest_ReportFormatWrapper_ReportFormat) EnumDescriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{23, 0, 0}
}

type GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod int32

const (
	GenerateReportRequest_DeliveryMethodWrapper_UNKNOWN GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod = 0
	// PDF Format
	GenerateReportRequest_DeliveryMethodWrapper_EMAIL_PDF GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod = 1
	// HTML Format
	GenerateReportRequest_DeliveryMethodWrapper_EMAIL_HTML GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod = 2
)

// Enum value maps for GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod.
var (
	GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod_name = map[int32]string{
		0: "UNKNOWN",
		1: "EMAIL_PDF",
		2: "EMAIL_HTML",
	}
	GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod_value = map[string]int32{
		"UNKNOWN":    0,
		"EMAIL_PDF":  1,
		"EMAIL_HTML": 2,
	}
)

func (x GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod) Enum() *GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod {
	p := new(GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod)
	*p = x
	return p
}

func (x GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_fixtures_tasks_proto_enumTypes[3].Descriptor()
}

func (GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod) Type() protoreflect.EnumType {
	return &file_fixtures_tasks_proto_enumTypes[3]
}

func (x GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod.Descriptor instead.
func (GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod) EnumDescriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{23, 1, 0}
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the task
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_fixtures_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTasksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter Tasks to those with one of the the given status
	Statuses []ListTasksRequest_Status `protobuf:"varint,1,rep,packed,name=statuses,proto3,enum=api.tasks.v1.ListTasksRequest_Status" json:"statuses,omitempty"`
	// Filter Tasks by ID
	Ids []string `protobuf:"bytes,2,rep,name=ids,proto3" json:"ids,omitempty"`
	// Limit page size
	PageSize      uint32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *ListTasksRequest) GetStatuses() []ListTasksRequest_Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListTasksRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListTasksRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	Id            string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Wrappers      *Wrappers `protobuf:"bytes,2,opt,name=wrappers,proto3" json:"wrappers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTaskRequest) GetWrappers() *Wrappers {
	if x != nil {
		return x.Wrappers
	}
	return nil
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{6}
}

type UpdateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the task
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTaskRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{8}
}

type UpdateTaskNestedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskNestedRequest) Reset() {
	*x = UpdateTaskNestedRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskNestedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskNestedRequest) ProtoMessage() {}

func (x *UpdateTaskNestedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskNestedRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskNestedRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTaskNestedRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the task
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the task
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Should send sms confirmation
	SmsConfirmation bool `protobuf:"varint,3,opt,name=sms_confirmation,json=smsConfirmation,proto3" json:"sms_confirmation,omitempty"`
	// Number of SMS retries
	SmsRetries uint32 `protobuf:"varint,4,opt,name=sms_retries,json=smsRetries,proto3" json:"sms_retries,omitempty"`
	// Deprecated: Do not use
	//
	// Deprecated: Marked as deprecated in fixtures/tasks.proto.
	TaskType string `protobuf:"bytes,5,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	// Test field for control_type functionality - should render as string input
	PriorityLevels []ListTasksRequest_Status `protobuf:"varint,6,rep,packed,name=priority_levels,json=priorityLevels,proto3,enum=api.tasks.v1.ListTasksRequest_Status" json:"priority_levels,omitempty"`
	// Test field for backwards compatibility - should render as multiselect (default)
	StatusFilters []ListTasksRequest_Status `protobuf:"varint,7,rep,packed,name=status_filters,json=statusFilters,proto3,enum=api.tasks.v1.ListTasksRequest_Status" json:"status_filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetSmsConfirmation() bool {
	if x != nil {
		return x.SmsConfirmation
	}
	return false
}

func (x *CreateTaskRequest) GetSmsRetries() uint32 {
	if x != nil {
		return x.SmsRetries
	}
	return 0
}

// Deprecated: Marked as deprecated in fixtures/tasks.proto.
func (x *CreateTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskRequest) GetPriorityLevels() []ListTasksRequest_Status {
	if x != nil {
		return x.PriorityLevels
	}
	return nil
}

func (x *CreateTaskRequest) GetStatusFilters() []ListTasksRequest_Status {
	if x != nil {
		return x.StatusFilters
	}
	return nil
}

type CreateTaskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{11}
}

func (x *CreateTaskResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AddCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The comment to add
	Comment       string `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentRequest) Reset() {
	*x = AddCommentRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRequest) ProtoMessage() {}

func (x *AddCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRequest.ProtoReflect.Descriptor instead.
func (*AddCommentRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{12}
}

func (x *AddCommentRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AddCommentRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AddCommentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the comment
	CommentId     string `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCommentResponse) Reset() {
	*x = AddCommentResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentResponse) ProtoMessage() {}

func (x *AddCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentResponse.ProtoReflect.Descriptor instead.
func (*AddCommentResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{13}
}

func (x *AddCommentResponse) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type UpdateCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the task
	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// The ID comment to update
	CommentId string `protobuf:"bytes,2,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	// The updated comment
	Comment       string `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	Timezone      string `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateCommentRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *UpdateCommentRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *UpdateCommentRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{15}
}

type TriggerTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Trigger event to subscribe to.
	Trigger       TriggerTaskRequest_TriggerEvent `protobuf:"varint,1,opt,name=trigger,proto3,enum=api.tasks.v1.TriggerTaskRequest_TriggerEvent" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTaskRequest) Reset() {
	*x = TriggerTaskRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTaskRequest) ProtoMessage() {}

func (x *TriggerTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTaskRequest.ProtoReflect.Descriptor instead.
func (*TriggerTaskRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{16}
}

func (x *TriggerTaskRequest) GetTrigger() TriggerTaskRequest_TriggerEvent {
	if x != nil {
		return x.Trigger
	}
	return TriggerTaskRequest_TRIGGER_EVENT_UNSPECIFIED
}

type TriggerTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookId     string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerTaskResponse) Reset() {
	*x = TriggerTaskResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerTaskResponse) ProtoMessage() {}

func (x *TriggerTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerTaskResponse.ProtoReflect.Descriptor instead.
func (*TriggerTaskResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{17}
}

func (x *TriggerTaskResponse) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *TriggerTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CustomActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomActionRequest) Reset() {
	*x = CustomActionRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomActionRequest) ProtoMessage() {}

func (x *CustomActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomActionRequest.ProtoReflect.Descriptor instead.
func (*CustomActionRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{18}
}

type CustomActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomActionResponse) Reset() {
	*x = CustomActionResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomActionResponse) ProtoMessage() {}

func (x *CustomActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomActionResponse.ProtoReflect.Descriptor instead.
func (*CustomActionResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{19}
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        *UpdateStatusRequest_Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateStatusRequest) GetStatus() *UpdateStatusRequest_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type UnusedButIncluded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abc           string                 `protobuf:"bytes,1,opt,name=abc,proto3" json:"abc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnusedButIncluded) Reset() {
	*x = UnusedButIncluded{}
	mi := &file_fixtures_tasks_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnusedButIncluded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnusedButIncluded) ProtoMessage() {}

func (x *UnusedButIncluded) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnusedButIncluded.ProtoReflect.Descriptor instead.
func (*UnusedButIncluded) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{21}
}

func (x *UnusedButIncluded) GetAbc() string {
	if x != nil {
		return x.Abc
	}
	return ""
}

type UnusedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xyz           string                 `protobuf:"bytes,1,opt,name=xyz,proto3" json:"xyz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnusedMessage) Reset() {
	*x = UnusedMessage{}
	mi := &file_fixtures_tasks_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnusedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnusedMessage) ProtoMessage() {}

func (x *UnusedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnusedMessage.ProtoReflect.Descriptor instead.
func (*UnusedMessage) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{22}
}

func (x *UnusedMessage) GetXyz() string {
	if x != nil {
		return x.Xyz
	}
	return ""
}

// Request object for GenerateReport
type GenerateReportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include active tasks only
	ActiveTasksOnly bool `protobuf:"varint,1,opt,name=active_tasks_only,json=activeTasksOnly,proto3" json:"active_tasks_only,omitempty"`
	// Report format
	Format GenerateReportRequest_ReportFormatWrapper_ReportFormat `protobuf:"varint,2,opt,name=format,proto3,enum=api.tasks.v1.GenerateReportRequest_ReportFormatWrapper_ReportFormat" json:"format,omitempty"`
	// Report delivery method
	Delivery      GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod `protobuf:"varint,3,opt,name=delivery,proto3,enum=api.tasks.v1.GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod" json:"delivery,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_fixtures_tasks_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{23}
}

func (x *GenerateReportRequest) GetActiveTasksOnly() bool {
	if x != nil {
		return x.ActiveTasksOnly
	}
	return false
}

func (x *GenerateReportRequest) GetFormat() GenerateReportRequest_ReportFormatWrapper_ReportFormat {
	if x != nil {
		return x.Format
	}
	return GenerateReportRequest_ReportFormatWrapper_UNKNOWN
}

func (x *GenerateReportRequest) GetDelivery() GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod {
	if x != nil {
		return x.Delivery
	}
	return GenerateReportRequest_DeliveryMethodWrapper_UNKNOWN
}

// Response object for GenerateReport
type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_fixtures_tasks_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{24}
}

// A bunch of wrapper messages
type Wrappers struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	DoubleValue   *wrapperspb.DoubleValue `protobuf:"bytes,1,opt,name=double_value,json=doubleValue,proto3" json:"double_value,omitempty"`
	FloatValue    *wrapperspb.FloatValue  `protobuf:"bytes,2,opt,name=float_value,json=floatValue,proto3" json:"float_value,omitempty"`
	Int64Value    *wrapperspb.Int64Value  `protobuf:"bytes,3,opt,name=int64_value,json=int64Value,proto3" json:"int64_value,omitempty"`
	Uint64Value   *wrapperspb.UInt64Value `protobuf:"bytes,4,opt,name=uint64_value,json=uint64Value,proto3" json:"uint64_value,omitempty"`
	Int32Value    *wrapperspb.Int32Value  `protobuf:"bytes,5,opt,name=int32_value,json=int32Value,proto3" json:"int32_value,omitempty"`
	Uint32Value   *wrapperspb.UInt32Value `protobuf:"bytes,6,opt,name=uint32_value,json=uint32Value,proto3" json:"uint32_value,omitempty"`
	BoolValue     *wrapperspb.BoolValue   `protobuf:"bytes,7,opt,name=bool_value,json=boolValue,proto3" json:"bool_value,omitempty"`
	StringValue   *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3" json:"string_value,omitempty"`
	BytesValue    *wrapperspb.BytesValue  `protobuf:"bytes,9,opt,name=bytes_value,json=bytesValue,proto3" json:"bytes_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wrappers) Reset() {
	*x = Wrappers{}
	mi := &file_fixtures_tasks_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wrappers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrappers) ProtoMessage() {}

func (x *Wrappers) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrappers.ProtoReflect.Descriptor instead.
func (*Wrappers) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{25}
}

func (x *Wrappers) GetDoubleValue() *wrapperspb.DoubleValue {
	if x != nil {
		return x.DoubleValue
	}
	return nil
}

func (x *Wrappers) GetFloatValue() *wrapperspb.FloatValue {
	if x != nil {
		return x.FloatValue
	}
	return nil
}

func (x *Wrappers) GetInt64Value() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64Value
	}
	return nil
}

func (x *Wrappers) GetUint64Value() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64Value
	}
	return nil
}

func (x *Wrappers) GetInt32Value() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32Value
	}
	return nil
}

func (x *Wrappers) GetUint32Value() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32Value
	}
	return nil
}

func (x *Wrappers) GetBoolValue() *wrapperspb.BoolValue {
	if x != nil {
		return x.BoolValue
	}
	return nil
}

func (x *Wrappers) GetStringValue() *wrapperspb.StringValue {
	if x != nil {
		return x.StringValue
	}
	return nil
}

func (x *Wrappers) GetBytesValue() *wrapperspb.BytesValue {
	if x != nil {
		return x.BytesValue
	}
	return nil
}

type UpdateStatusRequest_Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Abc           string                 `protobuf:"bytes,123,opt,name=abc,proto3" json:"abc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest_Status) Reset() {
	*x = UpdateStatusRequest_Status{}
	mi := &file_fixtures_tasks_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest_Status) ProtoMessage() {}

func (x *UpdateStatusRequest_Status) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest_Status.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest_Status) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{20, 0}
}

func (x *UpdateStatusRequest_Status) GetAbc() string {
	if x != nil {
		return x.Abc
	}
	return ""
}

// Wrapper for ReportFormat
type GenerateReportRequest_ReportFormatWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest_ReportFormatWrapper) Reset() {
	*x = GenerateReportRequest_ReportFormatWrapper{}
	mi := &file_fixtures_tasks_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest_ReportFormatWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest_ReportFormatWrapper) ProtoMessage() {}

func (x *GenerateReportRequest_ReportFormatWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest_ReportFormatWrapper.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest_ReportFormatWrapper) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{23, 0}
}

// Wrapper for DeliveryMethod
type GenerateReportRequest_DeliveryMethodWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest_DeliveryMethodWrapper) Reset() {
	*x = GenerateReportRequest_DeliveryMethodWrapper{}
	mi := &file_fixtures_tasks_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest_DeliveryMethodWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest_DeliveryMethodWrapper) ProtoMessage() {}

func (x *GenerateReportRequest_DeliveryMethodWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_tasks_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest_DeliveryMethodWrapper.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest_DeliveryMethodWrapper) Descriptor() ([]byte, []int) {
	return file_fixtures_tasks_proto_rawDescGZIP(), []int{23, 1}
}

var File_fixtures_tasks_proto protoreflect.FileDescriptor

const file_fixtures_tasks_proto_rawDesc = "" +
	"\n" +
	"\x14fixtures/tasks.proto\x12\fapi.tasks.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a&s12/protobuf/workato/annotations.proto\"*\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb5\x01\n" +
	"\x10ListTasksRequest\x12A\n" +
	"\bstatuses\x18\x01 \x03(\x0e2%.api.tasks.v1.ListTasksRequest.StatusR\bstatuses\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\tR\x03ids\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"/\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\x01\x12\f\n" +
	"\bARCHIVED\x10\x02\"=\n" +
	"\x11ListTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.api.tasks.v1.TaskR\x05tasks\"T\n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\bwrappers\x18\x02 \x01(\v2\x16.api.tasks.v1.WrappersR\bwrappers\"9\n" +
	"\x0fGetTaskResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.api.tasks.v1.TaskR\x04task\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"b\n" +
	"\x11UpdateTaskRequest\x129\n" +
	"\x02id\x18\x01 \x01(\tB)ʵ\x18%\n" +
	"#api.tasks.v1.TasksService/ListTasksR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x14\n" +
	"\x12UpdateTaskResponse\"A\n" +
	"\x17UpdateTaskNestedRequest\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.api.tasks.v1.TaskR\x04task\"\xf4\x02\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\vdescription\x18\x02 \x01(\tB\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNALR\vdescription\x12)\n" +
	"\x10sms_confirmation\x18\x03 \x01(\bR\x0fsmsConfirmation\x12\x1f\n" +
	"\vsms_retries\x18\x04 \x01(\rR\n" +
	"smsRetries\x12\x1f\n" +
	"\ttask_type\x18\x05 \x01(\tB\x02\x18\x01R\btaskType\x12\\\n" +
	"\x0fpriority_levels\x18\x06 \x03(\x0e2%.api.tasks.v1.ListTasksRequest.StatusB\fʵ\x18\b*\x06stringR\x0epriorityLevels\x12L\n" +
	"\x0estatus_filters\x18\a \x03(\x0e2%.api.tasks.v1.ListTasksRequest.StatusR\rstatusFilters\"$\n" +
	"\x12CreateTaskResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"R\n" +
	"\x11AddCommentRequest\x12#\n" +
	"\atask_id\x18\x01 \x01(\tB\n" +
	"\xe2A\x01\x02ʵ\x18\x02 \x01R\x06taskId\x12\x18\n" +
	"\acomment\x18\x02 \x01(\tR\acomment\"3\n" +
	"\x12AddCommentResponse\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"\x95\x01\n" +
	"\x14UpdateCommentRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x02 \x01(\tR\tcommentId\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12+\n" +
	"\btimezone\x18\x04 \x01(\tB\x0fʵ\x18\v\x1a\ttimezonesR\btimezone\"\x17\n" +
	"\x15UpdateCommentResponse\"\x8c\x02\n" +
	"\x12TriggerTaskRequest\x12G\n" +
	"\atrigger\x18\x01 \x01(\x0e2-.api.tasks.v1.TriggerTaskRequest.TriggerEventR\atrigger\"\xac\x01\n" +
	"\fTriggerEvent\x12\x1d\n" +
	"\x19TRIGGER_EVENT_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRIGGER_EVENT_TASK_CREATED\x10\x01\x12\x1e\n" +
	"\x1aTRIGGER_EVENT_TASK_UPDATED\x10\x02\x12\x1d\n" +
	"\x19TRIGGER_EVENT_TASK_CLOSED\x10\x03\x12\x1e\n" +
	"\x1aTRIGGER_EVENT_TASK_DELETED\x10\x04\"M\n" +
	"\x13TriggerTaskResponse\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"\x15\n" +
	"\x13CustomActionRequest\"\x16\n" +
	"\x14CustomActionResponse\"s\n" +
	"\x13UpdateStatusRequest\x12@\n" +
	"\x06status\x18\x01 \x01(\v2(.api.tasks.v1.UpdateStatusRequest.StatusR\x06status\x1a\x1a\n" +
	"\x06Status\x12\x10\n" +
	"\x03abc\x18{ \x01(\tR\x03abc\"%\n" +
	"\x11UnusedButIncluded\x12\x10\n" +
	"\x03abc\x18\x01 \x01(\tR\x03abc\"!\n" +
	"\rUnusedMessage\x12\x10\n" +
	"\x03xyz\x18\x01 \x01(\tR\x03xyz\"\xc2\x03\n" +
	"\x15GenerateReportRequest\x12*\n" +
	"\x11active_tasks_only\x18\x01 \x01(\bR\x0factiveTasksOnly\x12\\\n" +
	"\x06format\x18\x02 \x01(\x0e2D.api.tasks.v1.GenerateReportRequest.ReportFormatWrapper.ReportFormatR\x06format\x12d\n" +
	"\bdelivery\x18\x03 \x01(\x0e2H.api.tasks.v1.GenerateReportRequest.DeliveryMethodWrapper.DeliveryMethodR\bdelivery\x1ab\n" +
	"\x13ReportFormatWrapper\"K\n" +
	"\fReportFormat\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03CSV\x10\x01\x12\a\n" +
	"\x03TSV\x10\x02\x12\x1c\n" +
	"\x06HIDDEN\x10\x03\x1a\x10\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x1aU\n" +
	"\x15DeliveryMethodWrapper\"<\n" +
	"\x0eDeliveryMethod\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tEMAIL_PDF\x10\x01\x12\x0e\n" +
	"\n" +
	"EMAIL_HTML\x10\x02\"\x18\n" +
	"\x16GenerateReportResponse\"\xc1\x04\n" +
	"\bWrappers\x12?\n" +
	"\fdouble_value\x18\x01 \x01(\v2\x1c.google.protobuf.DoubleValueR\vdoubleValue\x12<\n" +
	"\vfloat_value\x18\x02 \x01(\v2\x1b.google.protobuf.FloatValueR\n" +
	"floatValue\x12<\n" +
	"\vint64_value\x18\x03 \x01(\v2\x1b.google.protobuf.Int64ValueR\n" +
	"int64Value\x12?\n" +
	"\fuint64_value\x18\x04 \x01(\v2\x1c.google.protobuf.UInt64ValueR\vuint64Value\x12<\n" +
	"\vint32_value\x18\x05 \x01(\v2\x1b.google.protobuf.Int32ValueR\n" +
	"int32Value\x12?\n" +
	"\fuint32_value\x18\x06 \x01(\v2\x1c.google.protobuf.UInt32ValueR\vuint32Value\x129\n" +
	"\n" +
	"bool_value\x18\a \x01(\v2\x1a.google.protobuf.BoolValueR\tboolValue\x12?\n" +
	"\fstring_value\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\vstringValue\x12<\n" +
	"\vbytes_value\x18\t \x01(\v2\x1b.google.protobuf.BytesValueR\n" +
	"bytesValue2\xf0\x12\n" +
	"\fTasksService\x12d\n" +
	"\vTriggerTask\x12 .api.tasks.v1.TriggerTaskRequest\x1a!.api.tasks.v1.TriggerTaskResponse\"\x10\x92A\a\n" +
	"\x05Tasksʵ\x18\x02\b\x01\x12{\n" +
	"\tListTasks\x12\x1e.api.tasks.v1.ListTasksRequest\x1a\x1f.api.tasks.v1.ListTasksResponse\"-ʵ\x18\x18\x12\x16\n" +
	"\n" +
	"tasks.name\x12\btasks.id\x82\xd3\xe4\x93\x02\v\x12\t/v1/tasks\x12\x80\x01\n" +
	"\n" +
	"CreateTask\x12\x1f.api.tasks.v1.CreateTaskRequest\x1a .api.tasks.v1.CreateTaskResponse\"/\x92A\r\n" +
	"\vTasks (NEW)ʵ\x18\a\"\x05Tasks\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/tasks\x12\xba\x01\n" +
	"\aGetTask\x12\x1c.api.tasks.v1.GetTaskRequest\x1a\x1d.api.tasks.v1.GetTaskResponse\"r\x92AY\n" +
	"\aTickets\n" +
	"\x05Tasks\n" +
	"\x06Issues\x12\n" +
	"Get a task\x1a3This description comes from the OpenAPI tag\n" +
	"abc\n" +
	"123\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/tasks/{id}\x12m\n" +
	"\x0ePrivateGetTask\x12\x1c.api.tasks.v1.GetTaskRequest\x1a\x1d.api.tasks.v1.GetTaskResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/private/tasks/{id}\x12t\n" +
	"\n" +
	"UpdateTask\x12\x1f.api.tasks.v1.UpdateTaskRequest\x1a .api.tasks.v1.UpdateTaskResponse\"#\x92A\a\n" +
	"\x05Tasks\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/tasks/{id}\x12\x85\x01\n" +
	"\x10UpdateTaskNested\x12%.api.tasks.v1.UpdateTaskNestedRequest\x1a .api.tasks.v1.UpdateTaskResponse\"(\x92A\a\n" +
	"\x05Tasks\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/tasks/{task.id}\x12\xab\x01\n" +
	"\n" +
	"DeleteTask\x12\x1f.api.tasks.v1.DeleteTaskRequest\x1a .api.tasks.v1.DeleteTaskResponse\"Z\x92AA\n" +
	"\x05Tasks\"8\n" +
	"\"Check out these docs to learn more\x12\x12https://google.com\x82\xd3\xe4\x93\x02\x10*\x0e/v1/tasks/{id}\x12\x9f\x01\n" +
	"\n" +
	"AddComment\x12\x1f.api.tasks.v1.AddCommentRequest\x1a .api.tasks.v1.AddCommentResponse\"N\x92A%\n" +
	"\rTask Comments\"\x14\x12\x12https://google.com\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/tasks/{task_id}/comment\x12\x9f\x01\n" +
	"\rUpdateComment\x12\".api.tasks.v1.UpdateCommentRequest\x1a#.api.tasks.v1.UpdateCommentResponse\"E\x92A\x0f\n" +
	"\rTask Comments\x82\xd3\xe4\x93\x02-:\x01*\x1a(/v1/tasks/{task_id}/comment/{comment_id}\x12a\n" +
	"\fCustomAction\x12!.api.tasks.v1.CustomActionRequest\x1a\".api.tasks.v1.CustomActionResponse\"\n" +
	"\x92A\a\n" +
	"\x05Tasks\x12\x91\x01\n" +
	"\x0eGenerateReport\x12#.api.tasks.v1.GenerateReportRequest\x1a$.api.tasks.v1.GenerateReportResponse\"4\x92A\a\n" +
	"\x05Tasks\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/tasks/action=generateReport\x12z\n" +
	"\fUpdateStatus\x12!.api.tasks.v1.UpdateStatusRequest\x1a\x16.google.protobuf.Empty\"/\x92A\a\n" +
	"\x05Tasks\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/tasks/{task_id}/status\x12\x87\x01\n" +
	"\x14UpdateStatusWithBody\x12!.api.tasks.v1.UpdateStatusRequest\x1a\x16.google.protobuf.Empty\"4\x92A\a\n" +
	"\x05Tasks\x82\xd3\xe4\x93\x02$:\x06status\"\x1a/v1/tasks/{task_id}/status\x12a\n" +
	"\x18UpdateStatusNoHttpOption\x12!.api.tasks.v1.UpdateStatusRequest\x1a\x16.google.protobuf.Empty\"\n" +
	"\x92A\a\n" +
	"\x05Tasks\x12m\n" +
	"\x11GetTaskIDsForUser\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"(\x92A\a\n" +
	"\x05Tasks\x82\xd3\xe4\x93\x02\x18:\x01*\x12\x13/v1/tasks/{user_id}\x12|\n" +
	"\x10GetTaskPrivately\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"8\x92A\a\n" +
	"\x05Tasks\xfa\xd2\xe4\x93\x02\n" +
	"\x12\bINTERNAL\x82\xd3\xe4\x93\x02\x18:\x01*\x12\x13/v1/tasks/{user_id}\x12\x90\x01\n" +
	"\x1cGetTaskPrivatelyButInWorkato\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"@\x92A\a\n" +
	"\x05Tasks\xfa\xd2\xe4\x93\x02\x12\x12\x10INTERNAL,WORKATO\x82\xd3\xe4\x93\x02\x18:\x01*\x12\x13/v1/tasks/{user_id}B\x16Z\x14fixtures/tasks;tasksb\x06proto3"

var (
	file_fixtures_tasks_proto_rawDescOnce sync.Once
	file_fixtures_tasks_proto_rawDescData []byte
)

func file_fixtures_tasks_proto_rawDescGZIP() []byte {
	file_fixtures_tasks_proto_rawDescOnce.Do(func() {
		file_fixtures_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fixtures_tasks_proto_rawDesc), len(file_fixtures_tasks_proto_rawDesc)))
	})
	return file_fixtures_tasks_proto_rawDescData
}

var file_fixtures_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_fixtures_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_fixtures_tasks_proto_goTypes = []any{
	(ListTasksRequest_Status)(0),                                    // 0: api.tasks.v1.ListTasksRequest.Status
	(TriggerTaskRequest_TriggerEvent)(0),                            // 1: api.tasks.v1.TriggerTaskRequest.TriggerEvent
	(GenerateReportRequest_ReportFormatWrapper_ReportFormat)(0),     // 2: api.tasks.v1.GenerateReportRequest.ReportFormatWrapper.ReportFormat
	(GenerateReportRequest_DeliveryMethodWrapper_DeliveryMethod)(0), // 3: api.tasks.v1.GenerateReportRequest.DeliveryMethodWrapper.DeliveryMethod
	(*Task)(nil),                                        // 4: api.tasks.v1.Task
	(*ListTasksRequest)(nil),                            // 5: api.tasks.v1.ListTasksRequest
	(*ListTasksResponse)(nil),                           // 6: api.tasks.v1.ListTasksResponse
	(*GetTaskRequest)(nil),                              // 7: api.tasks.v1.GetTaskRequest
	(*GetTaskResponse)(nil),                             // 8: api.tasks.v1.GetTaskResponse
	(*DeleteTaskRequest)(nil),                           // 9: api.tasks.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),                          // 10: api.tasks.v1.DeleteTaskResponse
	(*UpdateTaskRequest)(nil),                           // 11: api.tasks.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),                          // 12: api.tasks.v1.UpdateTaskResponse
	(*UpdateTaskNestedRequest)(nil),                     // 13: api.tasks.v1.UpdateTaskNestedRequest
	(*CreateTaskRequest)(nil),                           // 14: api.tasks.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),                          // 15: api.tasks.v1.CreateTaskResponse
	(*AddCommentRequest)(nil),                           // 16: api.tasks.v1.AddCommentRequest
	(*AddCommentResponse)(nil),                          // 17: api.tasks.v1.AddCommentResponse
	(*UpdateCommentRequest)(nil),                        // 18: api.tasks.v1.UpdateCommentRequest
	(*UpdateCommentResponse)(nil),                       // 19: api.tasks.v1.UpdateCommentResponse
	(*TriggerTaskRequest)(nil),                          // 20: api.tasks.v1.TriggerTaskRequest
	(*TriggerTaskResponse)(nil),                         // 21: api.tasks.v1.TriggerTaskResponse
	(*CustomActionRequest)(nil),                         // 22: api.tasks.v1.CustomActionRequest
	(*CustomActionResponse)(nil),                        // 23: api.tasks.v1.CustomActionResponse
	(*UpdateStatusRequest)(nil),                         // 24: api.tasks.v1.UpdateStatusRequest
	(*UnusedButIncluded)(nil),                           // 25: api.tasks.v1.UnusedButIncluded
	(*UnusedMessage)(nil),                               // 26: api.tasks.v1.UnusedMessage
	(*GenerateReportRequest)(nil),                       // 27: api.tasks.v1.GenerateReportRequest
	(*GenerateReportResponse)(nil),                      // 28: api.tasks.v1.GenerateReportResponse
	(*Wrappers)(nil),                                    // 29: api.tasks.v1.Wrappers
	(*UpdateStatusRequest_Status)(nil),                  // 30: api.tasks.v1.UpdateStatusRequest.Status
	(*GenerateReportRequest_ReportFormatWrapper)(nil),   // 31: api.tasks.v1.GenerateReportRequest.ReportFormatWrapper
	(*GenerateReportRequest_DeliveryMethodWrapper)(nil), // 32: api.tasks.v1.GenerateReportRequest.DeliveryMethodWrapper
	(*wrapperspb.DoubleValue)(nil),                      // 33: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),                       // 34: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),                       // 35: google.protobuf.Int64Value
	(*wrapperspb.UInt64Value)(nil),                      // 36: google.protobuf.UInt64Value
	(*wrapperspb.Int32Value)(nil),                       // 37: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil),                      // 38: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),                        // 39: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil),                      // 40: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),                       // 41: google.protobuf.BytesValue
	(*emptypb.Empty)(nil),                               // 42: google.protobuf.Empty
}
var file_fixtures_tasks_proto_depIdxs = []int32{
	0,  // 0: api.tasks.v1.ListTasksRequest.statuses:type_name -> api.tasks.v1.ListTasksRequest.Status
	4,  // 1: api.tasks.v1.ListTasksResponse.tasks:type_name -> api.tasks.v1.Task
	29, // 2: api.tasks.v1.GetTaskRequest.wrappers:type_name -> api.tasks.v1.Wrappers
	4,  // 3: api.tasks.v1.GetTaskResponse.task:type_name -> api.tasks.v1.Task
	4,  // 4: api.tasks.v1.UpdateTaskNestedRequest.task:type_name -> api.tasks.v1.Task
	0,  // 5: api.tasks.v1.CreateTaskRequest.priority_levels:type_name -> api.tasks.v1.ListTasksRequest.Status
	0,  // 6: api.tasks.v1.CreateTaskRequest.status_filters:type_name -> api.tasks.v1.ListTasksRequest.Status
	1,  // 7: api.tasks.v1.TriggerTaskRequest.trigger:type_name -> api.tasks.v1.TriggerTaskRequest.TriggerEvent
	30, // 8: api.tasks.v1.UpdateStatusRequest.status:type_name -> api.tasks.v1.UpdateStatusRequest.Status
	2,  // 9: api.tasks.v1.GenerateReportRequest.format:type_name -> api.tasks.v1.GenerateReportRequest.ReportFormatWrapper.ReportFormat
	3,  // 10: api.tasks.v1.GenerateReportRequest.delivery:type_name -> api.tasks.v1.GenerateReportRequest.DeliveryMethodWrapper.DeliveryMethod
	33, // 11: api.tasks.v1.Wrappers.double_value:type_name -> google.protobuf.DoubleValue
	34, // 12: api.tasks.v1.Wrappers.float_value:type_name -> google.protobuf.FloatValue
	35, // 13: api.tasks.v1.Wrappers.int64_value:type_name -> google.protobuf.Int64Value
	36, // 14: api.tasks.v1.Wrappers.uint64_value:type_name -> google.protobuf.UInt64Value
	37, // 15: api.tasks.v1.Wrappers.int32_value:type_name -> google.protobuf.Int32Value
	38, // 16: api.tasks.v1.Wrappers.uint32_value:type_name -> google.protobuf.UInt32Value
	39, // 17: api.tasks.v1.Wrappers.bool_value:type_name -> google.protobuf.BoolValue
	40, // 18: api.tasks.v1.Wrappers.string_value:type_name -> google.protobuf.StringValue
	41, // 19: api.tasks.v1.Wrappers.bytes_value:type_name -> google.protobuf.BytesValue
	20, // 20: api.tasks.v1.TasksService.TriggerTask:input_type -> api.tasks.v1.TriggerTaskRequest
	5,  // 21: api.tasks.v1.TasksService.ListTasks:input_type -> api.tasks.v1.ListTasksRequest
	14, // 22: api.tasks.v1.TasksService.CreateTask:input_type -> api.tasks.v1.CreateTaskRequest
	7,  // 23: api.tasks.v1.TasksService.GetTask:input_type -> api.tasks.v1.GetTaskRequest
	7,  // 24: api.tasks.v1.TasksService.PrivateGetTask:input_type -> api.tasks.v1.GetTaskRequest
	11, // 25: api.tasks.v1.TasksService.UpdateTask:input_type -> api.tasks.v1.UpdateTaskRequest
	13, // 26: api.tasks.v1.TasksService.UpdateTaskNested:input_type -> api.tasks.v1.UpdateTaskNestedRequest
	9,  // 27: api.tasks.v1.TasksService.DeleteTask:input_type -> api.tasks.v1.DeleteTaskRequest
	16, // 28: api.tasks.v1.TasksService.AddComment:input_type -> api.tasks.v1.AddCommentRequest
	18, // 29: api.tasks.v1.TasksService.UpdateComment:input_type -> api.tasks.v1.UpdateCommentRequest
	22, // 30: api.tasks.v1.TasksService.CustomAction:input_type -> api.tasks.v1.CustomActionRequest
	27, // 31: api.tasks.v1.TasksService.GenerateReport:input_type -> api.tasks.v1.GenerateReportRequest
	24, // 32: api.tasks.v1.TasksService.UpdateStatus:input_type -> api.tasks.v1.UpdateStatusRequest
	24, // 33: api.tasks.v1.TasksService.UpdateStatusWithBody:input_type -> api.tasks.v1.UpdateStatusRequest
	24, // 34: api.tasks.v1.TasksService.UpdateStatusNoHttpOption:input_type -> api.tasks.v1.UpdateStatusRequest
	42, // 35: api.tasks.v1.TasksService.GetTaskIDsForUser:input_type -> google.protobuf.Empty
	42, // 36: api.tasks.v1.TasksService.GetTaskPrivately:input_type -> google.protobuf.Empty
	42, // 37: api.tasks.v1.TasksService.GetTaskPrivatelyButInWorkato:input_type -> google.protobuf.Empty
	21, // 38: api.tasks.v1.TasksService.TriggerTask:output_type -> api.tasks.v1.TriggerTaskResponse
	6,  // 39: api.tasks.v1.TasksService.ListTasks:output_type -> api.tasks.v1.ListTasksResponse
	15, // 40: api.tasks.v1.TasksService.CreateTask:output_type -> api.tasks.v1.CreateTaskResponse
	8,  // 41: api.tasks.v1.TasksService.GetTask:output_type -> api.tasks.v1.GetTaskResponse
	8,  // 42: api.tasks.v1.TasksService.PrivateGetTask:output_type -> api.tasks.v1.GetTaskResponse
	12, // 43: api.tasks.v1.TasksService.UpdateTask:output_type -> api.tasks.v1.UpdateTaskResponse
	12, // 44: api.tasks.v1.TasksService.UpdateTaskNested:output_type -> api.tasks.v1.UpdateTaskResponse
	10, // 45: api.tasks.v1.TasksService.DeleteTask:output_type -> api.tasks.v1.DeleteTaskResponse
	17, // 46: api.tasks.v1.TasksService.AddComment:output_type -> api.tasks.v1.AddCommentResponse
	19, // 47: api.tasks.v1.TasksService.UpdateComment:output_type -> api.tasks.v1.UpdateCommentResponse
	23, // 48: api.tasks.v1.TasksService.CustomAction:output_type -> api.tasks.v1.CustomActionResponse
	28, // 49: api.tasks.v1.TasksService.GenerateReport:output_type -> api.tasks.v1.GenerateReportResponse
	42, // 50: api.tasks.v1.TasksService.UpdateStatus:output_type -> google.protobuf.Empty
	42, // 51: api.tasks.v1.TasksService.UpdateStatusWithBody:output_type -> google.protobuf.Empty
	42, // 52: api.tasks.v1.TasksService.UpdateStatusNoHttpOption:output_type -> google.protobuf.Empty
	42, // 53: api.tasks.v1.TasksService.GetTaskIDsForUser:output_type -> google.protobuf.Empty
	42, // 54: api.tasks.v1.TasksService.GetTaskPrivately:output_type -> google.protobuf.Empty
	42, // 55: api.tasks.v1.TasksService.GetTaskPrivatelyButInWorkato:output_type -> google.protobuf.Empty
	38, // [38:56] is the sub-list for method output_type
	20, // [20:38] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_fixtures_tasks_proto_init() }
func file_fixtures_tasks_proto_init() {
	if File_fixtures_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fixtures_tasks_proto_rawDesc), len(file_fixtures_tasks_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fixtures_tasks_proto_goTypes,
		DependencyIndexes: file_fixtures_tasks_proto_depIdxs,
		EnumInfos:         file_fixtures_tasks_proto_enumTypes,
		MessageInfos:      file_fixtures_tasks_proto_msgTypes,
	}.Build()
	File_fixtures_tasks_proto = out.File
	file_fixtures_tasks_proto_goTypes = nil
	file_fixtures_tasks_proto_depIdxs = nil
}
