# yamllint disable rule:line-length
---
name: Tests

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened]
  push:

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 2.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test & Coverage
        run: |
          go test ./...

      - name: Upload Coverage Result Artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeclimate-unit
          path: codeclimate.json
          retention-days: 1

      - uses: actions/setup-python@v2
      - name: Run pre commit linting
        uses: pre-commit/action@v3.0.1
